/*
 * Copyright (c) 2023 Félix Poulin-Bélanger. All rights reserved.
 */

#ifndef dynamic_info_h
#define dynamic_info_h

struct dynamic_info {
    const char* kern_version;
    bool kread_kqueue_workloop_ctl_supported;
    bool krkw_iosurface_supported;
    bool perf_supported;
    // struct proc
    u64 proc__p_list__le_prev;
    u64 proc__task;
    u64 proc__p_pid;
    u64 proc__p_fd__fd_ofiles;
    u64 proc__object_size;
    // struct task
    u64 task__map;
    // struct vm_map
    u64 vm_map__hdr_links_prev;
    u64 vm_map__hdr_links_next;
    u64 vm_map__min_offset;
    u64 vm_map__max_offset;
    u64 vm_map__hdr_nentries;
    u64 vm_map__hdr_nentries_u64;
    u64 vm_map__hdr_rb_head_store_rbh_root;
    u64 vm_map__pmap;
    u64 vm_map__hint;
    u64 vm_map__hole_hint;
    u64 vm_map__holes_list;
    u64 vm_map__object_size;
    // struct thread
    u64 thread__thread_id;
    // struct IOSurface
    u64 IOSurface__isa;
    u64 IOSurface__pixelFormat;
    u64 IOSurface__allocSize;
    u64 IOSurface__useCountPtr;
    u64 IOSurface__indexedTimestampPtr;
    u64 IOSurface__readDisplacement;
    // kernelcache static addresses (perf)
    u64 kernelcache__cdevsw;                          // "spec_open type" or "Can't mark ptc as kqueue ok"
    u64 kernelcache__gPhysBase;                       // "%s: illegal PA: 0x%llx; phys base 0x%llx, size 0x%llx"
    u64 kernelcache__gPhysSize;                       // (gPhysBase + 0x8)
    u64 kernelcache__gVirtBase;                       // "%s: illegal PA: 0x%llx; phys base 0x%llx, size 0x%llx"
    u64 kernelcache__perfmon_dev_open;                // "perfmon: attempt to open unsupported source: 0x%x"
    u64 kernelcache__perfmon_devices;                 // "perfmon: %s: devfs_make_node_clone failed"
    u64 kernelcache__ptov_table;                      // "%s: illegal PA: 0x%llx; phys base 0x%llx, size 0x%llx"
    u64 kernelcache__vn_kqfilter;                     // "Invalid knote filter on a vnode!"
};

const struct dynamic_info kern_versions[] = {
    // iOS 14.0 - 14.4, all devices
    {
        .kern_version = "////",
        .kread_kqueue_workloop_ctl_supported = false,
        .krkw_iosurface_supported = true,
        .perf_supported = false,
        .proc__p_list__le_prev = 0x0008,
        .proc__task = 0x10,
        .proc__p_pid = 0x0068,
        .proc__p_fd__fd_ofiles = 0x00f8,
        .proc__object_size = 0x04b0,
        .task__map = 0x0028,
        .vm_map__hdr_links_prev = 0x10,
        .vm_map__hdr_links_next = 0x18,
        .vm_map__min_offset = 0x20,
        .vm_map__max_offset = 0x28,
        .vm_map__hdr_nentries = 0x30,
        .vm_map__hdr_nentries_u64 = 0x30,
        .vm_map__hdr_rb_head_store_rbh_root = 0x40,
        .vm_map__pmap = 0x48,
        .vm_map__hint = 0xf0,
        .vm_map__hole_hint = 0xf8,
        .vm_map__holes_list = 0x100,
        .vm_map__object_size = 0x100,
        .IOSurface__isa = 0x0,
        .IOSurface__pixelFormat = 0xa4,
        .IOSurface__allocSize = 0xac,
        .IOSurface__useCountPtr = 0xc0,
        .IOSurface__indexedTimestampPtr = 0x260,
        .IOSurface__readDisplacement = 0x14,
        .thread__thread_id = 0,
    },
    // iOS 14.5 - 14.8, all devices
    {
        .kern_version = "////",
        .kread_kqueue_workloop_ctl_supported = false,
        .krkw_iosurface_supported = true,
        .perf_supported = false,
        .proc__p_list__le_prev = 0x0008,
        .proc__task = 0x10,
        .proc__p_pid = 0x0068,
        .proc__p_fd__fd_ofiles = 0x00f8,
        .proc__object_size = 0x04b0,
        .task__map = 0x0020,
        .vm_map__hdr_links_prev = 0x10,
        .vm_map__hdr_links_next = 0x18,
        .vm_map__min_offset = 0x20,
        .vm_map__max_offset = 0x28,
        .vm_map__hdr_nentries = 0x30,
        .vm_map__hdr_nentries_u64 = 0x30,
        .vm_map__hdr_rb_head_store_rbh_root = 0x40,
        .vm_map__pmap = 0x48,
        .vm_map__hint = 0xf0,
        .vm_map__hole_hint = 0xf8,
        .vm_map__holes_list = 0x100,
        .vm_map__object_size = 0x100,
        .IOSurface__isa = 0x0,
        .IOSurface__pixelFormat = 0xa4,
        .IOSurface__allocSize = 0xac,
        .IOSurface__useCountPtr = 0xc0,
        .IOSurface__indexedTimestampPtr = 0x260,
        .IOSurface__readDisplacement = 0x14,
        .thread__thread_id = 0,
    },
    // iOS 15.0 - 15.1.1, arm64
    {
        .kern_version = "////",
        .kread_kqueue_workloop_ctl_supported = false,
        .krkw_iosurface_supported = true,
        .perf_supported = false,
        .proc__p_list__le_prev = 0x0008,
        .proc__task = 0x10,
        .proc__p_pid = 0x0068,
        .proc__p_fd__fd_ofiles = 0x110,
        .proc__object_size = 0x04b0,
        .task__map = 0x0028,
        .vm_map__hdr_links_prev = 0x10,
        .vm_map__hdr_links_next = 0x18,
        .vm_map__min_offset = 0x20,
        .vm_map__max_offset = 0x28,
        .vm_map__hdr_nentries = 0x30,
        .vm_map__hdr_nentries_u64 = 0x30,
        .vm_map__hdr_rb_head_store_rbh_root = 0x40,
        .vm_map__pmap = 0x48,
        .vm_map__hint = 0x100,
        .vm_map__hole_hint = 0x108,
        .vm_map__holes_list = 0x110,
        .vm_map__object_size = 0x128,
        .IOSurface__isa = 0x0,
        .IOSurface__pixelFormat = 0xa4,
        .IOSurface__allocSize = 0xac,
        .IOSurface__useCountPtr = 0xc0,
        .IOSurface__indexedTimestampPtr = 0x260,
        .IOSurface__readDisplacement = 0x14,
        .thread__thread_id = 0,
    },
    // iOS 15.0 - 15.1.1, arm64e
    {
        .kern_version = "////",
        .kread_kqueue_workloop_ctl_supported = false,
        .krkw_iosurface_supported = true,
        .perf_supported = false,
        .proc__p_list__le_prev = 0x0008,
        .proc__task = 0x10,
        .proc__p_pid = 0x0068,
        .proc__p_fd__fd_ofiles = 0x100,
        .proc__object_size = 0x04b0,
        .task__map = 0x0028,
        .vm_map__hdr_links_prev = 0x10,
        .vm_map__hdr_links_next = 0x18,
        .vm_map__min_offset = 0x20,
        .vm_map__max_offset = 0x28,
        .vm_map__hdr_nentries = 0x30,
        .vm_map__hdr_nentries_u64 = 0x30,
        .vm_map__hdr_rb_head_store_rbh_root = 0x40,
        .vm_map__pmap = 0x48,
        .vm_map__hint = 0x100,
        .vm_map__hole_hint = 0x108,
        .vm_map__holes_list = 0x110,
        .vm_map__object_size = 0x128,
        .IOSurface__isa = 0x0,
        .IOSurface__pixelFormat = 0xa4,
        .IOSurface__allocSize = 0xac,
        .IOSurface__useCountPtr = 0xc0,
        .IOSurface__indexedTimestampPtr = 0x260,
        .IOSurface__readDisplacement = 0x14,
        .thread__thread_id = 0,
    },
    // iOS 15.2 - 15.3.1, arm64
    {
        .kern_version = "////",
        .kread_kqueue_workloop_ctl_supported = false,
        .krkw_iosurface_supported = true,
        .perf_supported = false,
        .proc__p_list__le_prev = 0x0008,
        .proc__task = 0x10,
        .proc__p_pid = 0x0068,
        .proc__p_fd__fd_ofiles = 0x00f8,
        .proc__object_size = 0x04b0,
        .task__map = 0x0028,
        .vm_map__hdr_links_prev = 0x10,
        .vm_map__hdr_links_next = 0x18,
        .vm_map__min_offset = 0x20,
        .vm_map__max_offset = 0x28,
        .vm_map__hdr_nentries = 0x30,
        .vm_map__hdr_nentries_u64 = 0x30,
        .vm_map__hdr_rb_head_store_rbh_root = 0x40,
        .vm_map__pmap = 0x48,
        .vm_map__hint = 0x100,
        .vm_map__hole_hint = 0x108,
        .vm_map__holes_list = 0x110,
        .vm_map__object_size = 0x128,
        .IOSurface__isa = 0x0,
        .IOSurface__pixelFormat = 0xa4,
        .IOSurface__allocSize = 0xac,
        .IOSurface__useCountPtr = 0xc0,
        .IOSurface__indexedTimestampPtr = 0x260,
        .IOSurface__readDisplacement = 0x14,
        .thread__thread_id = 0,
    },
    // iOS 15.2 - 15.3.1, arm64e
    {
        .kern_version = "////",
        .kread_kqueue_workloop_ctl_supported = false,
        .krkw_iosurface_supported = true,
        .perf_supported = false,
        .proc__p_list__le_prev = 0x0008,
        .proc__task = 0x10,
        .proc__p_pid = 0x0068,
        .proc__p_fd__fd_ofiles = 0x00f8,
        .proc__object_size = 0x04b0,
        .task__map = 0x0028,
        .vm_map__hdr_links_prev = 0x10,
        .vm_map__hdr_links_next = 0x18,
        .vm_map__min_offset = 0x20,
        .vm_map__max_offset = 0x28,
        .vm_map__hdr_nentries = 0x30,
        .vm_map__hdr_nentries_u64 = 0x30,
        .vm_map__hdr_rb_head_store_rbh_root = 0x40,
        .vm_map__pmap = 0x48,
        .vm_map__hint = 0x100,
        .vm_map__hole_hint = 0x108,
        .vm_map__holes_list = 0x110,
        .vm_map__object_size = 0x128,
        .IOSurface__isa = 0x0,
        .IOSurface__pixelFormat = 0xa4,
        .IOSurface__allocSize = 0xac,
        .IOSurface__useCountPtr = 0xc0,
        .IOSurface__indexedTimestampPtr = 0x260,
        .IOSurface__readDisplacement = 0x14,
        .thread__thread_id = 0,
    },
    // iOS 15.4 - 15.8, arm64
    {
        .kern_version = "////",
        .kread_kqueue_workloop_ctl_supported = false,
        .krkw_iosurface_supported = true,
        .perf_supported = false,
        .proc__p_list__le_prev = 0x0008,
        .proc__task = 0x10,
        .proc__p_pid = 0x0068,
        .proc__p_fd__fd_ofiles = 0x00f8,
        .proc__object_size = 0x04b0,
        .task__map = 0x0028,
        .vm_map__hdr_links_prev = 0x10,
        .vm_map__hdr_links_next = 0x18,
        .vm_map__min_offset = 0x20,
        .vm_map__max_offset = 0x28,
        .vm_map__hdr_nentries = 0x30,
        .vm_map__hdr_nentries_u64 = 0x30,
        .vm_map__hdr_rb_head_store_rbh_root = 0x38,
        .vm_map__pmap = 0x40,
        .vm_map__hint = 0x78,
        .vm_map__hole_hint = 0x80,
        .vm_map__holes_list = 0x88,
        .vm_map__object_size = 0xa0,
        .IOSurface__isa = 0x0,
        .IOSurface__pixelFormat = 0xa4,
        .IOSurface__allocSize = 0xac,
        .IOSurface__useCountPtr = 0xc0,
        .IOSurface__indexedTimestampPtr = 0x260,
        .IOSurface__readDisplacement = 0x14,
        .thread__thread_id = 0,
    },
    // iOS 15.4 - 15.7.8, arm64e
    {
        .kern_version = "////",
        .kread_kqueue_workloop_ctl_supported = false,
        .krkw_iosurface_supported = true,
        .perf_supported = false,
        .proc__p_list__le_prev = 0x0008,
        .proc__task = 0x10,
        .proc__p_pid = 0x0068,
        .proc__p_fd__fd_ofiles = 0x00f8,
        .proc__object_size = 0x04b0,
        .task__map = 0x0028,
        .vm_map__hdr_links_prev = 0x10,
        .vm_map__hdr_links_next = 0x18,
        .vm_map__min_offset = 0x20,
        .vm_map__max_offset = 0x28,
        .vm_map__hdr_nentries = 0x30,
        .vm_map__hdr_nentries_u64 = 0x30,
        .vm_map__hdr_rb_head_store_rbh_root = 0x38,
        .vm_map__pmap = 0x40,
        .vm_map__hint = 0x78,
        .vm_map__hole_hint = 0x80,
        .vm_map__holes_list = 0x88,
        .vm_map__object_size = 0xa0,
        .IOSurface__isa = 0x0,
        .IOSurface__pixelFormat = 0xa4,
        .IOSurface__allocSize = 0xac,
        .IOSurface__useCountPtr = 0xc0,
        .IOSurface__indexedTimestampPtr = 0x260,
        .IOSurface__readDisplacement = 0x14,
        .thread__thread_id = 0,
    },
    // iOS 16.5 - iPhone 14 Pro Max
    {
        .kern_version = "Darwin Kernel Version 22.5.0: Mon Apr 24 21:09:28 PDT 2023; root:xnu-8796.122.4~1/RELEASE_ARM64_T8120",
        .kread_kqueue_workloop_ctl_supported = false,
        .perf_supported = true,
        .proc__p_list__le_prev = 0x0008,
        .proc__task = 0x0000,
        .proc__p_pid = 0x0060,
        .proc__p_fd__fd_ofiles = 0x00f8,
        .proc__object_size = 0x0730,
        .task__map = 0x0028,
        .vm_map__hdr_links_prev = 0x10,
        .vm_map__hdr_links_next = 0x18,
        .vm_map__min_offset = 0x20,
        .vm_map__max_offset = 0x28,
        .vm_map__hdr_nentries = 0x30,
        .vm_map__hdr_nentries_u64 = 0x30,
        .vm_map__hdr_rb_head_store_rbh_root = 0x38,
        .vm_map__pmap = 0x40,
        .vm_map__hint = 0x98,
        .vm_map__hole_hint = 0xa0,
        .vm_map__holes_list = 0xa8,
        .vm_map__object_size = 0xc0,
        .thread__thread_id = 0,
        .kernelcache__cdevsw = 0xfffffff00a419208,
        .kernelcache__gPhysBase = 0xfffffff007934010,
        .kernelcache__gPhysSize = 0xfffffff007934018,
        .kernelcache__gVirtBase = 0xfffffff0079321e8,
        .kernelcache__perfmon_dev_open = 0xfffffff007eecfc0,
        .kernelcache__perfmon_devices = 0xfffffff00a457500,
        .kernelcache__ptov_table = 0xfffffff0078e7178,
        .kernelcache__vn_kqfilter = 0xfffffff007f39b28,
    },
    // iOS 16.6 - iPhone 12 Pro
    // T1SZ_BOOT must be changed to 25 instead of 17
    {
        .kern_version = "Darwin Kernel Version 22.6.0: Wed Jun 28 20:50:15 PDT 2023; root:xnu-8796.142.1~1/RELEASE_ARM64_T8101",
        .kread_kqueue_workloop_ctl_supported = false,
        .perf_supported = true,
        .proc__p_list__le_prev = 0x0008,
        .proc__task = 0x0000,
        .proc__p_pid = 0x0060,
        .proc__p_fd__fd_ofiles = 0x00f8,
        .proc__object_size = 0x0730,
        .task__map = 0x0028,
        .vm_map__hdr_links_prev = 0x10,
        .vm_map__hdr_links_next = 0x18,
        .vm_map__min_offset = 0x20,
        .vm_map__max_offset = 0x28,
        .vm_map__hdr_nentries = 0x30,
        .vm_map__hdr_nentries_u64 = 0x30,
        .vm_map__hdr_rb_head_store_rbh_root = 0x38,
        .vm_map__pmap = 0x40,
        .vm_map__hint = 0x98,
        .vm_map__hole_hint = 0xa0,
        .vm_map__holes_list = 0xa8,
        .vm_map__object_size = 0xc0,
        .thread__thread_id = 0,
        .kernelcache__cdevsw = 0xfffffff00a4a5288,
        .kernelcache__gPhysBase = 0xfffffff0079303b8,
        .kernelcache__gPhysSize = 0xfffffff0079303c0,
        .kernelcache__gVirtBase = 0xfffffff00792e570,
        .kernelcache__perfmon_dev_open = 0xfffffff007ef4278,
        .kernelcache__perfmon_devices = 0xfffffff00a4e5320,
        .kernelcache__ptov_table = 0xfffffff0078e38f0,
        .kernelcache__vn_kqfilter = 0xfffffff007f42f40,
    },
    // macOS 13.4 - MacBook Air (M2, 2022)
    {
        .kern_version = "todo",
        .kread_kqueue_workloop_ctl_supported = false,
        .perf_supported = false,
        .proc__p_list__le_prev = 0x0008,
        .proc__task = 0x0000,
        .proc__p_pid = 0x0060,
        .proc__p_fd__fd_ofiles = 0x00f8,
        .proc__object_size = 0x0778,
        .task__map = 0x0028,
        .vm_map__hdr_links_prev = 0x10,
        .vm_map__hdr_links_next = 0x18,
        .vm_map__min_offset = 0x20,
        .vm_map__max_offset = 0x28,
        .vm_map__hdr_nentries = 0x30,
        .vm_map__hdr_nentries_u64 = 0x30,
        .vm_map__hdr_rb_head_store_rbh_root = 0x38,
        .vm_map__pmap = 0x40,
        .vm_map__hint = 0x80,
        .vm_map__hole_hint = 0x88,
        .vm_map__holes_list = 0x90,
        .vm_map__object_size = 0xa8,
        .thread__thread_id = 0,
        .kernelcache__cdevsw = 0,
        .kernelcache__gPhysBase = 0,
        .kernelcache__gPhysSize = 0,
        .kernelcache__gVirtBase = 0,
        .kernelcache__perfmon_dev_open = 0,
        .kernelcache__perfmon_devices = 0,
        .kernelcache__ptov_table = 0,
        .kernelcache__vn_kqfilter = 0,
    },
    // macOS 13.5 - MacBook Air (M2, 2022)
    {
        .kern_version = "Darwin Kernel Version 22.6.0: Wed Jul  5 22:17:35 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8112",
        .kread_kqueue_workloop_ctl_supported = false,
        .perf_supported = false,
        .proc__p_list__le_prev = 0x0008,
        .proc__task = 0x0000,
        .proc__p_pid = 0x0060,
        .proc__p_fd__fd_ofiles = 0x00f8,
        .proc__object_size = 0x0778,
        .task__map = 0x0028,
        .vm_map__hdr_links_prev = 0x10,
        .vm_map__hdr_links_next = 0x18,
        .vm_map__min_offset = 0x20,
        .vm_map__max_offset = 0x28,
        .vm_map__hdr_nentries = 0x30,
        .vm_map__hdr_nentries_u64 = 0x30,
        .vm_map__hdr_rb_head_store_rbh_root = 0x38,
        .vm_map__pmap = 0x40,
        .vm_map__hint = 0x80,
        .vm_map__hole_hint = 0x88,
        .vm_map__holes_list = 0x90,
        .vm_map__object_size = 0xa8,
        .thread__thread_id = 0,
        .kernelcache__cdevsw = 0,
        .kernelcache__gPhysBase = 0,
        .kernelcache__gPhysSize = 0,
        .kernelcache__gVirtBase = 0,
        .kernelcache__perfmon_dev_open = 0,
        .kernelcache__perfmon_devices = 0,
        .kernelcache__ptov_table = 0,
        .kernelcache__vn_kqfilter = 0,
    },
};

#endif /* dynamic_info_h */
